apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: java-app
  name: java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: java-app
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/springtemplatedockerized-default: "true"
        io.kompose.service: java-app
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:latest
        command:
        - sh
        - -c
        - |-
          until nc -z java-db 5432; do
            sleep 1
          done
      containers:
        - env:
            - name: DATABASE_PASSWORD
              value: postgres
            - name: DATABASE_URL
              value: jdbc:postgresql://java-db:5432/demo
            - name: DATABASE_USERNAME
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          image: detivenc/java_app:1.0
          name: java-app
          ports:
            - containerPort: 8080
              hostPort: 0
              protocol: TCP
      restartPolicy: Always
